version: '3'

services:
  popsim:
    build: .
    image: popsim
    ports: 
      - 80:80
    volumes: 
      - ./populationsim-taz:/ps_taz
      - ./populationsim-taz-2040:/ps_taz_2040
      - ./populationsim-taz-2050:/ps_taz_2050
